### PR TITLE
Handle unexpected character encodings

### LINKED ISSUE #15: UTF-8 error
I tried to run this in my Rails app, but I got the error:

```
discover-unused-partials-0.3.1/lib/discover-unused-partials.rb:88:in `strip!': invalid byte sequence in UTF-8 (ArgumentError)
```

Any hints?

### PR DESCRIPTION
**Pull request by geoffharcourt**
Some files cause encoding issues that break the template crawler. The
reports on #15 range from Ruby version to template type to file encoding
differences.

This change uses a somewhat brute force approach to work around the
issue by dropping unexpected characters inspired by this blog post:

https://thoughtbot.com/blog/fight-back-utf-8-invalid-byte-sequences

After this change we were able to crawl and parse our templates
successfully.

Close #15

### CODE REVIEW

File: lib/discover-unused-partials.rb [hunk 1]
```diff
@@ -85,7 +85,10 @@ def process_partials(files)
       files.each do |file|
         File.open(file) do |f|
           f.each do |line|
-            line.strip!
+            line = line.
+              encode("UTF-8", "binary", invalid: :replace, undef: :replace, replace: "").
+              strip
```
Comment (geoffharcourt) [inline lib/discover-unused-partials.rb:90]: https://thoughtbot.com/blog/fight-back-utf-8-invalid-byte-sequences

**Comment by vinibaggio** [comment]
@geoffharcourt thanks for your contribution!! I will make a new release.

**Comment by vinibaggio** [comment]
@geoffharcourt 0.3.5 was released with this fix.
